export const environment = {
  apiUrl: `${window.location.protocol}//${window.location.hostname}:5000`,

  shopTagMap: {
    fr: {
      'alimentaire': 'alimentaire',
      'boulangerie': 'bakery',
      'boucherie': 'butcher',
      'primeur': 'greengrocer',
      'supermarché': 'supermarket',
      'épicerie': 'convenience',
      'kiosque': 'kiosk',
      'café': 'cafe',
      'salon de thé': 'tea',
      'fast food': 'fast_food',
      'pub': 'pub',
      'bar': 'bar',
      'aire de restauration': 'food_court',
      'glacier': 'ice_cream',
      'chocolaterie': 'chocolate',
      'confiserie': 'confectionery',
      'caviste': 'wine',
      'magasin de bières': 'beer',
      'épicerie fine': 'deli',
      'fromagerie': 'cheese',
      'poissonnerie': 'seafood',
      'pâtisserie': 'pastry',
      'miel': 'honey',
      'magasin bio': 'organic',
      'épices': 'spices',
      'pâtes': 'pasta',
    },
    en: {
      food: 'alimentaire',
      bakery: 'bakery',
      butcher: 'butcher',
      greengrocer: 'greengrocer',
      supermarket: 'supermarket',
      convenience: 'convenience',
      kiosk: 'kiosk',
      coffee: 'cafe',
      tea: 'tea',
      fast_food: 'fast_food',
      pub: 'pub',
      bar: 'bar',
      food_court: 'food_court',
      ice_cream: 'ice_cream',
      chocolate: 'chocolate',
      sweet_shop: 'confectionery',
      wine_shop: 'wine',
      beer: 'beer',
      deli: 'deli',
      cheese: 'cheese',
      seafood: 'seafood',
      'pastry shop': 'pastry',
      honey: 'honey',
      organic: 'organic',
      spices: 'spices',
      pasta: 'pasta',
    },
    es: {
      alimentario: 'alimentaire',
      panadería: 'bakery',
      carnicería: 'butcher',
      frutería: 'greengrocer',
      supermercado: 'supermarket',
      tienda: 'convenience',
      quiosco: 'kiosk',
      cafetería: 'cafe',
      salón_de_té: 'tea',
      comida_rápida: 'fast_food',
      pub: 'pub',
      bar: 'bar',
      patio_de_comidas: 'food_court',
      heladería: 'ice_cream',
      chocolatería: 'chocolate',
      confitería: 'confectionery',
      vinoteca: 'wine',
      tienda_de_cervezas: 'beer',
      delicatessen: 'deli',
      quesería: 'cheese',
      pescadería: 'seafood',
      pastelería: 'pastry',
      miel: 'honey',
      tienda_ecológica: 'organic',
      especias: 'spices',
      pasta: 'pasta',
    }
  } as Record<string, Record<string, string>>,

  iconMap: {
    alimentaire: '/images/alimentaire.png',
    bakery: '/images/bakery.png',
    butcher: '/images/butcher.png',
    greengrocer: '/images/greengrocer.png',
    supermarket: '/images/supermarket.png',
    convenience: '/images/convenience.png',
    kiosk: '/images/kiosk.png',
    cafe: '/images/cafe.png',
    tea: '/images/tea.png',
    fast_food: '/images/fast_food.png',
    pub: '/images/pub.png',
    bar: '/images/bar.png',
    food_court: '/images/food_court.png',
    ice_cream: '/images/ice_cream.png',
    chocolate: '/images/chocolate.png',
    confectionery: '/images/confectionery.png',
    wine: '/images/wine.png',
    beer: '/images/beer.png',
    deli: '/images/deli.png',
    cheese: '/images/cheese.png',
    seafood: '/images/seafood.png',
    pastry: '/images/pastry.png',
    honey: '/images/honey.png',
    organic: '/images/organic.png',
    spices: '/images/spices.png',
    pasta: '/images/pasta.png',
  }
};
